server:
  port: 20001

# 服务名称
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #通过服务名称访问服务，并开启小写
          enabled: true
          lower-case-service-id: true
      routes:
        - id: business
          uri: lb://business
          predicates:
          - Path=/business/**
        - id: consumer
          uri: lb://consumer
          predicates:
          - Path=/consumer/**
        - id: producer
          uri: lb://producer
          predicates:
          - Path=/producer/**
    nacos:
      discovery:
        server-addr: 192.168.179.128:8848
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN