server:
  port: 20007

# 服务名称
spring:
  application:
    name: redis
  #redis配置
  redis:
    database: 0
    host: 192.168.179.128
    port: 6379
    password: qatest
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0